#!/bin/bash -e

package_version="1.0-${1:-'dev'}";

package_filename="no_tool_bar_${package_version}.zip"

package_root="$( cd "$( dirname "$0" )" && pwd )"
package_target="${package_root}/target/"
package_src_root="${package_root}/src/main/"

# list of files to be added to the package
# the first element in the list is assumed to be the plugin main file
package_files=( "no-tool-bar.php" )

package_absolute_files=( "${package_files[@]/#/${package_src_root}/}" )

rm -rf "${package_target}"
mkdir "${package_target}"

cp "${package_absolute_files[@]}" "${package_target}"

sed -i -e "/^Version:/ s/$/ ${package_version}/" "${package_target}${package_files[0]}"
sed -i -e "s/\/\/DEPLOY //g" "${package_target}${package_files[0]}"

cd "${package_target}"
zip -r "${package_filename}" "${package_files[@]}"
